export const jobs = [
  {
    id: "CT-5274",
    contractor: "Solarize",
    customer: "Janvier, Paulette",
    phone: "860-555-0192",
    email: "paulette.janvier@email.com",
    street: "84 Elmwood Ave",
    city: "Waterbury",
    state: "CT",
    zip: "06704",
    hoa: false,
    systemSize: "14.4",
    panelCount: 36,
    watt: 400,
    inverter: "Enphase IQ8A",
    battery: false,
    roofType: "Asphalt shingle",
    rep: "Tommy",
    crew: ["Tommy", "Jake"],
    partner: "SolarCrew NE",
    financer: "GoodLeap",
    invoiceNumber: "INV-2965",
    installCost: 11628,
    contractAmount: 11628,
    m1Due: true,
    m1Received: true,
    m2Due: false,
    m2Received: false,
    utilityCompany: "Eversource CT",
    permitStatus: "Approved",
    stage: 40,
    status: "Install Complete",
    installDate: "2026-03-03",
    inspectionDate: "",
    ptoDate: "",
    siteSurveyDate: "2026-01-15",
    interconnectionStatus: "Submitted",
    nextAction: "Schedule inspection",
    adders: [{ description: "200A panel upgrade", cost: 2200 }],
    notes: "Homeowner confirmed access. Panel upgrade included.",
    createdAt: "2026-01-10",
    updatedAt: "2026-03-03",
    deal: "Loan",
    module: "QCell 400",
    qty: 36,
    ageD: 76,
    stageD: 28.9,
    buildPartner: "Solarize Home Energy",
    monitoring: "Active",
    monitoringAlerts: 3,
    lifetimeProduction: "28.9 MWh",
    contractSigned: "2026-01-10",
    fileCreated: "2026-01-10",
    syncDate: "2026-03-19",
  },
  {
    id: "MA-5092",
    contractor: "Empower",
    customer: "Ciampoli, Mary",
    phone: "413-555-0847",
    email: "mary.ciampoli@email.com",
    street: "219 Oakland St",
    city: "Springfield",
    state: "MA",
    zip: "01108",
    hoa: false,
    systemSize: "7.8",
    panelCount: 20,
    watt: 390,
    inverter: "Enphase IQ8M",
    battery: false,
    roofType: "Asphalt shingle",
    rep: "Tommy",
    crew: ["Tommy", "Jake"],
    partner: "SolarCrew NE",
    financer: "Cash",
    invoiceNumber: "INV-2967",
    installCost: 6240,
    contractAmount: 6240,
    m1Due: true,
    m1Received: true,
    m2Due: false,
    m2Received: false,
    utilityCompany: "Eversource MA",
    permitStatus: "Approved",
    stage: 50,
    status: "Rescheduled / Issue",
    installDate: "2026-03-03",
    inspectionDate: "",
    ptoDate: "",
    siteSurveyDate: "2026-01-20",
    interconnectionStatus: "Pending redesign",
    nextAction: "Utility redesign submission",
    adders: [{ description: "Meter upgrade", cost: 800 }],
    notes: "Meter upgrade required before PTO. Utility rejected first submission. Need exception form.",
    createdAt: "2026-01-18",
    updatedAt: "2026-03-05",
    deal: "Loan",
    module: "QCell 400",
    qty: 20,
    ageD: 73,
    stageD: 22.2,
    buildPartner: "Solarize Home Energy",
    monitoring: "Pending_communication",
    monitoringAlerts: 1,
    lifetimeProduction: "22.2 MWh",
    contractSigned: "2026-01-18",
    fileCreated: "2026-01-18",
    syncDate: "2026-03-19",
  },
  {
    id: "NH-4685",
    contractor: "Empower",
    customer: "James, Marta",
    phone: "603-555-0334",
    email: "marta.james@email.com",
    street: "47 Crown St",
    city: "Nashua",
    state: "NH",
    zip: "03060",
    hoa: true,
    systemSize: "8.7",
    panelCount: 22,
    watt: 400,
    inverter: "SolarEdge HD Wave",
    battery: true,
    roofType: "Metal",
    rep: "Kyle",
    crew: ["Kyle", "Matt"],
    partner: "SolarCrew NE",
    financer: "LightReach",
    invoiceNumber: "INV-2969",
    installCost: 6960,
    contractAmount: 6960,
    m1Due: true,
    m1Received: true,
    m2Due: true,
    m2Received: false,
    utilityCompany: "Eversource NH",
    permitStatus: "Approved",
    stage: 80,
    status: "Inspection Passed",
    installDate: "2026-03-04",
    inspectionDate: "2026-03-10",
    ptoDate: "",
    siteSurveyDate: "2026-01-22",
    interconnectionStatus: "Approved",
    nextAction: "Collect M2, submit PTO packet",
    adders: [],
    notes: "Inspection passed 3/10. HOA approval on file.",
    createdAt: "2026-01-20",
    updatedAt: "2026-03-10",
    deal: "Loan",
    module: "SolarEdge HD Wave",
    qty: 22,
    ageD: 58,
    stageD: 33.8,
    buildPartner: "Solarize Home Energy",
    monitoring: "Active",
    monitoringAlerts: 0,
    lifetimeProduction: "33.8 MWh",
    contractSigned: "2026-01-20",
    fileCreated: "2026-01-22",
    syncDate: "2026-03-19",
  },
  {
    id: "ME-5021",
    contractor: "Empower",
    customer: "Brookings, Timothy",
    phone: "207-555-0561",
    email: "timothy.brookings@email.com",
    street: "88 Foreside Rd",
    city: "Portland",
    state: "ME",
    zip: "04101",
    hoa: false,
    systemSize: "7.2",
    panelCount: 18,
    watt: 400,
    inverter: "Enphase IQ8A",
    battery: false,
    roofType: "Asphalt shingle",
    rep: "Matt",
    crew: ["Matt"],
    partner: "Maine Solar Partners",
    financer: "GoodLeap",
    invoiceNumber: "INV-2971",
    installCost: 5680,
    contractAmount: 5680,
    m1Due: false,
    m1Received: false,
    m2Due: false,
    m2Received: false,
    utilityCompany: "CMP",
    permitStatus: "In Review",
    stage: 30,
    status: "Rescheduled / Issue",
    installDate: "2026-03-06",
    inspectionDate: "",
    ptoDate: "",
    siteSurveyDate: "2026-02-01",
    interconnectionStatus: "Submitted",
    nextAction: "Diagnose monitoring issue — Envoy offline",
    adders: [],
    notes: "Monitoring offline since install. CT check needed. Envoy not communicating.",
    createdAt: "2026-01-28",
    updatedAt: "2026-03-06",
    deal: "Loan",
    module: "Enphase IQ8A",
    qty: 18,
    ageD: 47,
    stageD: 15.2,
    buildPartner: "Maine Solar Partners",
    monitoring: "Pending_communication",
    monitoringAlerts: 2,
    lifetimeProduction: "15.2 MWh",
    contractSigned: "2026-01-28",
    fileCreated: "2026-02-01",
    syncDate: "2026-03-19",
  },
  {
    id: "CT-5301",
    contractor: "Solarize",
    customer: "Rivera, Carlos",
    phone: "203-555-0773",
    email: "carlos.rivera@email.com",
    street: "412 Whalley Ave",
    city: "New Haven",
    state: "CT",
    zip: "06511",
    hoa: false,
    systemSize: "10.2",
    panelCount: 26,
    watt: 390,
    inverter: "Enphase IQ8A",
    battery: false,
    roofType: "Asphalt shingle",
    rep: "Kyle",
    crew: ["Tommy", "Jake"],
    partner: "SolarCrew NE",
    financer: "Mosaic",
    invoiceNumber: "INV-2972",
    installCost: 8160,
    contractAmount: 8160,
    m1Due: false,
    m1Received: false,
    m2Due: false,
    m2Received: false,
    utilityCompany: "Eversource CT",
    permitStatus: "Submitted",
    stage: 20,
    status: "Scheduled",
    installDate: "2026-03-18",
    inspectionDate: "",
    ptoDate: "",
    siteSurveyDate: "2026-02-10",
    interconnectionStatus: "Not submitted",
    nextAction: "Await permit approval, prep install crew",
    adders: [],
    notes: "Submitted to town 3/7. Standard residential, no conditions expected.",
    createdAt: "2026-02-05",
    updatedAt: "2026-03-07",
    deal: "Loan",
    module: "Enphase IQ8A",
    qty: 26,
    ageD: 42,
    stageD: 18.5,
    buildPartner: "SolarCrew NE",
    monitoring: "Active",
    monitoringAlerts: 0,
    lifetimeProduction: "18.5 MWh",
    contractSigned: "2026-02-05",
    fileCreated: "2026-02-10",
    syncDate: "2026-03-19",
  },
  {
    id: "MA-5110",
    contractor: "Empower",
    customer: "Okafor, Ngozi",
    phone: "508-555-0219",
    email: "ngozi.okafor@email.com",
    street: "91 Burncoat St",
    city: "Worcester",
    state: "MA",
    zip: "01606",
    hoa: false,
    systemSize: "9.6",
    panelCount: 24,
    watt: 400,
    inverter: "SolarEdge HD Wave",
    battery: true,
    roofType: "Asphalt shingle",
    rep: "Matt",
    crew: ["Matt", "Jake"],
    partner: "SolarCrew NE",
    financer: "GoodLeap",
    invoiceNumber: "",
    installCost: 7680,
    contractAmount: 7680,
    m1Due: false,
    m1Received: false,
    m2Due: false,
    m2Received: false,
    utilityCompany: "National Grid",
    permitStatus: "Not Submitted",
    stage: 20,
    status: "Scheduled",
    installDate: "2026-03-25",
    inspectionDate: "",
    ptoDate: "",
    siteSurveyDate: "2026-02-18",
    interconnectionStatus: "Not submitted",
    nextAction: "Finalize design, submit permit",
    adders: [],
    notes: "Structural engineering sign-off pending.",
    createdAt: "2026-02-15",
    updatedAt: "2026-03-01",
    deal: "Loan",
    module: "SolarEdge HD Wave",
    qty: 24,
    ageD: 32,
    stageD: 21.4,
    buildPartner: "SolarCrew NE",
    monitoring: "Active",
    monitoringAlerts: 0,
    lifetimeProduction: "21.4 MWh",
    contractSigned: "2026-02-15",
    fileCreated: "2026-02-18",
    syncDate: "2026-03-19",
  },
];

export const permits = [
  {
    id: "PR-001",
    jobId: "CT-5274",
    customer: "Janvier, Paulette",
    town: "Waterbury, CT",
    status: "Approved",
    submittedDate: "2026-02-10",
    approvedDate: "2026-02-24",
    submissionMethod: "Online portal",
    ahj: "Waterbury Building Dept",
    nextAction: "Schedule inspection",
    notes: "Panel upgrade permit also pulled.",
  },
  {
    id: "PR-002",
    jobId: "MA-5092",
    customer: "Ciampoli, Mary",
    town: "Springfield, MA",
    status: "Utility Redesign Needed",
    submittedDate: "2026-02-12",
    approvedDate: null,
    submissionMethod: "Email",
    ahj: "Springfield Inspections",
    nextAction: "Revise meter/disconnect plan",
    notes: "Utility requested load-side tap redesign.",
  },
  {
    id: "PR-003",
    jobId: "NH-4685",
    customer: "James, Marta",
    town: "Nashua, NH",
    status: "Approved",
    submittedDate: "2026-02-05",
    approvedDate: "2026-02-18",
    submissionMethod: "Online portal",
    ahj: "Nashua Code Enforcement",
    nextAction: "Submit PTO packet",
    notes: "Smooth approval. No conditions.",
  },
  {
    id: "PR-004",
    jobId: "ME-5021",
    customer: "Brookings, Timothy",
    town: "Portland, ME",
    status: "In Review",
    submittedDate: "2026-02-28",
    approvedDate: null,
    submissionMethod: "In person",
    ahj: "Portland Inspections",
    nextAction: "Follow up with AHJ",
    notes: "Town has 15-day review window. Day 13.",
  },
  {
    id: "PR-005",
    jobId: "CT-5301",
    customer: "Rivera, Carlos",
    town: "New Haven, CT",
    status: "Submitted",
    submittedDate: "2026-03-07",
    approvedDate: null,
    submissionMethod: "Online portal",
    ahj: "New Haven Building Dept",
    nextAction: "Await approval",
    notes: "Standard residential. No conditions expected.",
  },
  {
    id: "PR-006",
    jobId: "MA-5110",
    customer: "Okafor, Ngozi",
    town: "Worcester, MA",
    status: "Not Submitted",
    submittedDate: null,
    approvedDate: null,
    submissionMethod: "TBD",
    ahj: "Worcester Inspections",
    nextAction: "Finalize design before submission",
    notes: "Waiting on structural sign-off.",
  },
];

export const invoices = [
  {
    id: "INV-2965",
    jobId: "CT-5274",
    customer: "Janvier, Paulette",
    type: "M1",
    amount: 9302,
    status: "Paid",
    dueDate: "2026-02-15",
    paidDate: "2026-02-14",
    financer: "GoodLeap",
    notes: "",
  },
  {
    id: "INV-2966",
    jobId: "CT-5274",
    customer: "Janvier, Paulette",
    type: "M2",
    amount: 2326,
    status: "Pending",
    dueDate: "2026-03-10",
    paidDate: null,
    financer: "GoodLeap",
    notes: "Awaiting inspection completion.",
  },
  {
    id: "INV-2967",
    jobId: "MA-5092",
    customer: "Ciampoli, Mary",
    type: "M1",
    amount: 4992,
    status: "Paid",
    dueDate: "2026-02-18",
    paidDate: "2026-02-17",
    financer: "Cash",
    notes: "",
  },
  {
    id: "INV-2968",
    jobId: "MA-5092",
    customer: "Ciampoli, Mary",
    type: "M2",
    amount: 1248,
    status: "Overdue",
    dueDate: "2026-03-05",
    paidDate: null,
    financer: "Cash",
    notes: "PTO hold blocking final payment.",
  },
  {
    id: "INV-2969",
    jobId: "NH-4685",
    customer: "James, Marta",
    type: "M1",
    amount: 5568,
    status: "Paid",
    dueDate: "2026-02-20",
    paidDate: "2026-02-19",
    financer: "LightReach",
    notes: "",
  },
  {
    id: "INV-2970",
    jobId: "NH-4685",
    customer: "James, Marta",
    type: "M2",
    amount: 1392,
    status: "Pending",
    dueDate: "2026-03-15",
    paidDate: null,
    financer: "LightReach",
    notes: "Inspection passed 3/10. M2 due.",
  },
  {
    id: "INV-2971",
    jobId: "ME-5021",
    customer: "Brookings, Timothy",
    type: "M1",
    amount: 4544,
    status: "Pending",
    dueDate: "2026-02-25",
    paidDate: null,
    financer: "GoodLeap",
    notes: "On hold — monitoring issue unresolved.",
  },
  {
    id: "INV-2972",
    jobId: "CT-5301",
    customer: "Rivera, Carlos",
    type: "M1",
    amount: 6528,
    status: "Pending",
    dueDate: "2026-03-20",
    paidDate: null,
    financer: "Mosaic",
    notes: "Awaiting permit approval before M1 trigger.",
  },
];

export const serviceItems = [
  {
    id: "SV-101",
    jobId: "CT-5274",
    site: "84 Elmwood Ave, Waterbury, CT",
    customer: "Janvier, Paulette",
    issue: "Consumption CT check",
    urgency: "Medium",
    status: "Open",
    createdDate: "2026-03-01",
    assignedTo: "Matt",
    notes: "Production looks off. CT may be reversed.",
  },
  {
    id: "SV-102",
    jobId: "MA-5092",
    site: "219 Oakland St, Springfield, MA",
    customer: "Ciampoli, Mary",
    issue: "PTO / meter exception follow-up",
    urgency: "High",
    status: "Open",
    createdDate: "2026-03-05",
    assignedTo: "Tommy",
    notes: "Utility rejected first submission. Need exception form.",
  },
  {
    id: "SV-103",
    jobId: "CT-5301",
    site: "526 Hartford Turnpike, Shrewsbury, MA",
    customer: "Delgado, Rosa",
    issue: "Commercial closeout items",
    urgency: "Medium",
    status: "In Progress",
    createdDate: "2026-02-28",
    assignedTo: "Kyle",
    notes: "Three punch list items remain. Scheduled for 3/18.",
  },
  {
    id: "SV-104",
    jobId: "ME-5021",
    site: "88 Foreside Rd, Portland, ME",
    customer: "Brookings, Timothy",
    issue: "Monitoring offline since install",
    urgency: "High",
    status: "Open",
    createdDate: "2026-03-06",
    assignedTo: "Matt",
    notes: "Envoy not communicating. Remote attempt failed.",
  },
  {
    id: "SV-105",
    jobId: "NH-4685",
    site: "47 Crown St, Nashua, NH",
    customer: "Petrov, Annika",
    issue: "Roof leak reported near flashing",
    urgency: "High",
    status: "Scheduled",
    createdDate: "2026-03-10",
    assignedTo: "Kyle",
    notes: "Customer reported drip in attic. Site visit 3/17.",
  },
];

export const scheduleItems = [
  {
    id: "SCH-001",
    type: "Install",
    jobId: "CT-5301",
    customer: "Rivera, Carlos",
    site: "412 Whalley Ave, New Haven, CT",
    date: "2026-03-18",
    crew: ["Tommy", "Jake"],
    startTime: "7:30 AM",
    duration: "Full day",
    notes: "10.2 kW. Panel upgrade included.",
    status: "Confirmed",
  },
  {
    id: "SCH-002",
    type: "Install",
    jobId: "MA-5110",
    customer: "Okafor, Ngozi",
    site: "91 Burncoat St, Worcester, MA",
    date: "2026-03-25",
    crew: ["Matt", "Jake"],
    startTime: "7:30 AM",
    duration: "Full day",
    notes: "9.6 kW. Complex roof.",
    status: "Tentative",
  },
  {
    id: "SCH-003",
    type: "Inspection",
    jobId: "CT-5274",
    customer: "Janvier, Paulette",
    site: "84 Elmwood Ave, Waterbury, CT",
    date: "2026-03-17",
    crew: ["Tommy"],
    startTime: "10:00 AM",
    duration: "2 hours",
    notes: "Town inspector. Bring panel upgrade permit.",
    status: "Confirmed",
  },
  {
    id: "SCH-004",
    type: "Service",
    jobId: "NH-4685",
    customer: "Petrov, Annika",
    site: "47 Crown St, Nashua, NH",
    date: "2026-03-17",
    crew: ["Kyle"],
    startTime: "1:00 PM",
    duration: "3 hours",
    notes: "Roof flashing leak.",
    status: "Confirmed",
  },
  {
    id: "SCH-005",
    type: "Service",
    jobId: "ME-5021",
    customer: "Brookings, Timothy",
    site: "88 Foreside Rd, Portland, ME",
    date: "2026-03-19",
    crew: ["Matt"],
    startTime: "9:00 AM",
    duration: "Half day",
    notes: "Envoy offline. Bring laptop for config.",
    status: "Confirmed",
  },
];
